### ISSUE TITLE
create brigade airtable account

### ISSUE THREAD

**Issue by markdav-is** [OpenEugene/mural-tour-2021-plan#5]
I'd like to use airtable to prototype the back end.  if you can create and airtable account, then a workstpace for the tour and invite me that would be awesome.  I could do it in my own airtable, but that feels wrong.  I sent you my airtable email address in a direct message

**Comment by Michael-McKinley** [comment]
@nohorse - We had already done this ... and you already accepted the invite
![image](https://user-images.githubusercontent.com/5976433/66695170-02919400-ec73-11e9-8d9d-91d4c4bab2f2.png)

**Comment by Michael-McKinley** [comment]
Assigned to me, and closed as completed.

**Comment by markdav-is** [comment]
Very nice!

Sent from my BlackBerry - the most secure mobile device
